ktor:
  deployment:
    port: 8080
  application:
    modules:
      - louchez.emmanuel.ApplicationKt.module

db:
  url: "jdbc:postgresql://localhost:5432/user_management"
  user: "postgres"
  password: "postgres"

jwt:
  secret: "une-clé-secrète-longue-et-aléatoire"
  issuer: "user-management"
  audience: "users"
