ktor:
  deployment:
    port: 8080
  application:
    modules:
      - louchez.emmanuel.SerializationKt.configureSerialization
      - louchez.emmanuel.StatusPagesKt.configureStatusPages
      - louchez.emmanuel.RoutingKt.configureRouting
      - louchez.emmanuel.Application.module

db:
  url: "jdbc:postgresql://localhost:5432/user_management"
  user: "postgres"
  password: "postgres"
